version: '3.6'
services:
  postgres:
    image: postgres:12
    container_name: "postgres_hasura_dev"
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  hasura-graphql:
    image: hasura/graphql-engine:v1.3.3
    container_name: "hasura_dev"
    ports:
      - "9010:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432
      HASURA_GRAPHQL_ADMIN_SECRET: questionsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
volumes:
  db_data_pg: